INSERT INTO T_MUSIC(ID, LYRICS, AUTHOR_NAME, RATING) VALUES(1, 'Music 1', 'anup', 4);
INSERT INTO T_MUSIC(ID, LYRICS, AUTHOR_NAME, RATING) VALUES(2, 'Music 2', 'anup', 4);
INSERT INTO T_MUSIC(ID, LYRICS, AUTHOR_NAME, RATING) VALUES(3, 'Music 3', 'anup', 4);
INSERT INTO T_MUSIC(ID, LYRICS, AUTHOR_NAME, RATING) VALUES(4, 'Music 4', 'anup', 4);